<?php $product_id = $block->getRequest()->getParam('id'); ?>
<div id="codliar-knockout-faq" data-bind="scope:'codilar-ko-faq'" data-id="<?= $product_id ?>">
<!-- ko template: getTemplate() --><!-- /ko -->
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "codilar-ko-faq": {
                    "component": "Codilar_Faq/js/faq"
                }
            }
        }
    }
}
</script>
</div>
